services:

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
      target: dev
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service:8081
      CATALOG_SERVICE_URL: http://catalog-service:8082
      ORDER_SERVICE_URL: http://order-service:8083
      INVENTORY_SERVICE_URL: http://inventory-service:8084
      PAYMENT_SERVICE_URL: http://payment-service:8085
    volumes:
      - .:/app                     # mount source for hot reload
    command: air -c services/gateway/.air.toml
    restart: "no"
    depends_on:
      user-service:
        condition: service_healthy