root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/gateway ."
  bin = "tmp/gateway"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "1s"

[log]
  time = true